version: "3"
services:
  node_app1:
    image: node-app
    container_name: node_app1
    build: .
    ports:
      - "3001:3000"

  node_app2:
    image: node-app
    container_name: node_app2
    build: .
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - node_app1
      - node_app2
